# Dependencies
markdown:         redcarpet
highlighter:      pygments
gems: [jekyll-paginate]
# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Brandon Cane
tagline:          'A Jekyll theme'
description:      'Hmmm'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Brandon Cane'
  url:            https://twitter.com/mdo

paginate:         5
paginate_path: "page:num"
# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/BrandonCane507
