# Dependencies
markdown:         redcarpet
highlighter:      pygments
gems: [jekyll-paginate]
# Permalinks
permalink:        pretty
#relative_permalinks: true
plugins: - jekyll-seo-tag
# Setup
title:            Brandon Cane
tagline:          'A Jekyll theme'
description:      'A site for Brandon and things'
baseurl:          /

author:
  name:           'Brandon Cane'

paginate:         5
paginate_path: "page:num"
# Custom vars

github:
  repo:           https://github.com/BrandonCane507
