# Dependencies
markdown:         redcarpet
permalink:        /:title
highlighter:      pygments
gems: [jekyll-paginate]
plugins:
  - jekyll-feed
  - jekyll-seo-tag
# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Brandon Cane
#tagline:          'A Jekyll theme'
description:      'A site for Brandon and things'
baseurl:          /brandoncane507.github.io

author:
  name:           'Brandon Cane'
  url:            https://sites.pitt.edu/~blc95/

paginate:         5
paginate_path: "page:num"
# Custom vars

github:
  repo:           https://github.com/BrandonCane507
